name: Run Selenium Daily

on:
  schedule:
    - cron: "27 11 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager

      - name: Run Selenium script
        run: |
          python main.py
